# Generated by Django 5.0.6 on 2024-05-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_name', models.CharField(max_length=10)),
                ('tire_description', models.CharField(max_length=100)),
                ('tire_price', models.IntegerField()),
            ],
        ),
    ]
