# Generated by Django 5.0.6 on 2024-05-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_body', models.CharField(max_length=500)),
                ('ontact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
