# Generated by Django 5.0.6 on 2024-05-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='ontact_email',
            new_name='contact_email',
        ),
    ]
